# Generated by Django 3.0.8 on 2020-07-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkbox_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sex', models.CharField(choices=[(0, '男'), (1, '女')], default=0, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Combo_Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(0, '繁體中文'), (1, '英文')], default=0, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Datetime_Picker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_picker', models.DateField(default=['%d/%m/%Y'])),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Text_Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20)),
                ('keyword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('Sex', models.CharField(choices=[(0, '男'), (1, '女')], default=0, max_length=2)),
                ('Language', models.CharField(choices=[(0, '繁體中文'), (1, '英文')], default=0, max_length=2)),
            ],
        ),
    ]
